Use certs to auth against kafka brokers

diff --git a/bitnami/shared/upstream.yaml b/bitnami/shared/upstream.yaml
--- a/bitnami/shared/upstream.yaml
+++ b/bitnami/shared/upstream.yaml
@@ -7,7 +7,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: cluster-metrics
@@ -21,7 +21,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: kafka
@@ -36,7 +36,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: metrics
@@ -103,7 +103,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
 data:
@@ -118,10 +118,14 @@ data:
         if [[ $KAFKA_CFG_PROCESS_ROLES == "" ]]; then
             export KAFKA_CFG_BROKER_ID="$(grep "broker.id" "/bitnami/kafka/data/meta.properties" | awk -F '=' '{print $2}')"
         else
-            export KAFKA_CFG_BROKER_ID="$(grep "node.id" "/bitnami/kafka/data/meta.properties" | awk -F '=' '{print $2}')"
+            export KAFKA_CFG_NODE_ID="$(grep "node.id" "/bitnami/kafka/data/meta.properties" | awk -F '=' '{print $2}')"
         fi
     else
-        export KAFKA_CFG_BROKER_ID="$((ID + 0))"
+        if [[ $KAFKA_CFG_PROCESS_ROLES == "" ]]; then
+            export KAFKA_CFG_BROKER_ID="$((ID + 0))"
+        else
+            export KAFKA_CFG_NODE_ID="$((ID + 0))"
+        fi
     fi
 
     if [[ $KAFKA_CFG_PROCESS_ROLES == *"controller"* ]]; then
@@ -129,7 +133,7 @@ data:
         pod_id=0
         while :
         do 
-            VOTERS="${VOTERS}$node_id@kafka-shared-$pod_id.kafka-shared-headless.sys-pubsub.svc.cluster.local:9095"
+            VOTERS="${VOTERS}$node_id@kafka-shared-$pod_id.kafka-shared-headless.sys-pubsub.svc.cluster.local:9093"
             node_id=$(( $node_id + 1 ))
             pod_id=$(( $pod_id + 1 ))
             if [[ $pod_id -ge 3 ]]; then
@@ -140,6 +144,29 @@ data:
         done
         export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=$VOTERS
     fi
+    mkdir -p /opt/bitnami/kafka/config/certs
+    PEM_CA="/certs-${ID}/ca.crt"
+    PEM_CERT="/certs-${ID}/tls.crt"
+    PEM_KEY="/certs-${ID}/tls.key"
+    if [[ -f "$PEM_CERT" ]] && [[ -f "$PEM_KEY" ]]; then
+        CERT_DIR="/opt/bitnami/kafka/config/certs"
+        PEM_CA_LOCATION="${CERT_DIR}/kafka.truststore.pem"
+        PEM_CERT_LOCATION="${CERT_DIR}/kafka.keystore.pem"
+            if [[ -f "$PEM_CA" ]]; then
+                cp "$PEM_CA" "$PEM_CA_LOCATION"
+                cp "$PEM_CERT" "$PEM_CERT_LOCATION"
+            else
+                echo "PEM_CA not provided, and auth.tls.pemChainIncluded was not true. One of these values must be set when using PEM type for TLS."
+                exit 1
+            fi
+
+        # Ensure the key used PEM format with PKCS#8
+        openssl pkcs8 -topk8 -nocrypt -in "$PEM_KEY" > "/opt/bitnami/kafka/config/certs/kafka.keystore.key"
+    else
+        echo "Couldn't find the expected PEM files! They are mandatory when encryption via TLS is enabled."
+        exit 1
+    fi
+    export KAFKA_TLS_TRUSTSTORE_FILE="/opt/bitnami/kafka/config/certs/kafka.truststore.pem"
 
     # Configure zookeeper client
 
@@ -153,7 +180,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: metrics
@@ -183,7 +210,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: cluster-metrics
@@ -213,7 +240,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: kafka
@@ -227,12 +254,12 @@ spec:
       protocol: TCP
       targetPort: kafka-client
     - name: tcp-internal
-      port: 9093
+      port: 9094
       protocol: TCP
       targetPort: kafka-internal
     - name: tcp-controller
       protocol: TCP
-      port: 9095
+      port: 9093
       targetPort: kafka-ctlr
   selector:
     app.kubernetes.io/name: kafka
@@ -247,7 +274,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: kafka
@@ -273,7 +300,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: cluster-metrics
@@ -288,7 +315,7 @@ spec:
     metadata:
       labels:
         app.kubernetes.io/name: kafka
-        helm.sh/chart: kafka-21.4.4
+        helm.sh/chart: kafka-22.0.1
         app.kubernetes.io/instance: 21.4.2
         app.kubernetes.io/managed-by: Helm
         app.kubernetes.io/component: cluster-metrics
@@ -315,7 +342,7 @@ spec:
       serviceAccountName: kafka-shared-exporter
       containers:
         - name: kafka-exporter
-          image: docker.io/bitnami/kafka-exporter:1.6.0-debian-11-r73
+          image: docker.io/bitnami/kafka-exporter:1.6.0-debian-11-r80
           imagePullPolicy: "IfNotPresent"
           securityContext:
             runAsNonRoot: true
@@ -329,6 +356,7 @@ spec:
               --kafka.server=kafka-shared-0.kafka-shared-headless.sys-pubsub.svc.cluster.local:9092 \
               --kafka.server=kafka-shared-1.kafka-shared-headless.sys-pubsub.svc.cluster.local:9092 \
               --kafka.server=kafka-shared-2.kafka-shared-headless.sys-pubsub.svc.cluster.local:9092 \
+              --tls.enabled \
               --web.listen-address=:9308
           ports:
             - name: metrics
@@ -347,7 +375,7 @@ metadata:
   namespace: "sys-pubsub"
   labels:
     app.kubernetes.io/name: kafka
-    helm.sh/chart: kafka-21.4.4
+    helm.sh/chart: kafka-22.0.1
     app.kubernetes.io/instance: 21.4.2
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: kafka
@@ -367,12 +395,12 @@ spec:
     metadata:
       labels:
         app.kubernetes.io/name: kafka
-        helm.sh/chart: kafka-21.4.4
+        helm.sh/chart: kafka-22.0.1
         app.kubernetes.io/instance: 21.4.2
         app.kubernetes.io/managed-by: Helm
         app.kubernetes.io/component: kafka
       annotations:
-        checksum/jmx-configuration: ee179e2450adb5048f72210f7fe289af76001fd3843c3c31bf767b08dbce4f4a
+        checksum/jmx-configuration: a27966b2ad71d451b063a2887941041bdb898f8b9305f89f8280e8a55bc4f40f
     spec:
       
       hostNetwork: false
@@ -397,7 +425,7 @@ spec:
       serviceAccountName: kafka-shared
       containers:
         - name: kafka
-          image: docker.io/bitnami/kafka:3.4.0-debian-11-r15
+          image: docker.io/bitnami/kafka:3.4.0-debian-11-r22
           imagePullPolicy: "IfNotPresent"
           securityContext:
             allowPrivilegeEscalation: false
@@ -421,15 +449,23 @@ spec:
             - name: KAFKA_INTER_BROKER_LISTENER_NAME
               value: "INTERNAL"
             - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
-              value: "INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT"
+              value: "INTERNAL:SSL,CLIENT:SSL,CONTROLLER:PLAINTEXT"
             - name: KAFKA_CFG_LISTENERS
-              value: "INTERNAL://:9093,CLIENT://:9092,CONTROLLER://:9095"
+              value: "INTERNAL://:9094,CLIENT://:9092,CONTROLLER://:9093"
             - name: KAFKA_CFG_ADVERTISED_LISTENERS
-              value: "INTERNAL://$(MY_POD_NAME).kafka-shared-headless.sys-pubsub.svc.cluster.local:9093,CLIENT://$(MY_POD_NAME).kafka-shared-headless.sys-pubsub.svc.cluster.local:9092"
+              value: "INTERNAL://$(MY_POD_NAME).kafka-shared-headless.sys-pubsub.svc.cluster.local:9094,CLIENT://$(MY_POD_NAME).kafka-shared-headless.sys-pubsub.svc.cluster.local:9092"
             - name: ALLOW_PLAINTEXT_LISTENER
               value: "yes"
             - name: KAFKA_ZOOKEEPER_PROTOCOL
               value: PLAINTEXT
+            - name: KAFKA_TLS_TYPE
+              value: "PEM"
+            - name: KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
+              value: "https"
+            - name: KAFKA_TLS_CLIENT_AUTH
+              value: "required"
+            - name: KAFKA_CERTIFICATE_PASSWORD
+              value: ""
             - name: JMX_PORT
               value: "5555"
             - name: KAFKA_VOLUME_DIR
@@ -500,9 +536,9 @@ spec:
             - name: kafka-client
               containerPort: 9092
             - name: kafka-internal
-              containerPort: 9093
+              containerPort: 9094
             - name: kafka-ctlr
-              containerPort: 9095
+              containerPort: 9093
           livenessProbe:
             failureThreshold: 3
             initialDelaySeconds: 10
@@ -530,8 +566,17 @@ spec:
             - name: scripts
               mountPath: /scripts/setup.sh
               subPath: setup.sh
+            - name: kafka-certs-0
+              mountPath: /certs-0
+              readOnly: true
+            - name: kafka-certs-1
+              mountPath: /certs-1
+              readOnly: true
+            - name: kafka-certs-2
+              mountPath: /certs-2
+              readOnly: true
         - name: jmx-exporter
-          image: docker.io/bitnami/jmx-exporter:0.18.0-debian-11-r5
+          image: docker.io/bitnami/jmx-exporter:0.18.0-debian-11-r12
           imagePullPolicy: "IfNotPresent"
           securityContext:
             runAsNonRoot: true
@@ -562,6 +607,18 @@ spec:
         - name: jmx-config
           configMap:
             name: kafka-shared-jmx-configuration
+        - name: kafka-certs-0
+          secret:
+            secretName: kafka-shared-0-tls
+            defaultMode: 256
+        - name: kafka-certs-1
+          secret:
+            secretName: kafka-shared-1-tls
+            defaultMode: 256
+        - name: kafka-certs-2
+          secret:
+            secretName: kafka-shared-2-tls
+            defaultMode: 256
         - name: logs
           emptyDir: {}
   volumeClaimTemplates:
