Bitnami kraft auth (#23)
* Use certs to auth against kafka brokers

* Add certificates to kafka-exporter

* Disable hostname verification for clients

* Create root CA certificate and use it in the issuer

* Lock down cluster by enabling acls

* Fix CA cert

* Introduce ClusterIssuer and add kyverno policy to manage users

---------

Co-authored-by: Catalin Ilea <cilea@utilitywarehouse.co.uk>

diff --git a/bitnami/shared/upstream/kafka.yaml b/bitnami/shared/upstream/kafka.yaml
--- a/bitnami/shared/upstream/kafka.yaml
+++ b/bitnami/shared/upstream/kafka.yaml
@@ -7,7 +7,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: cluster-metrics
@@ -21,7 +21,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: kafka
@@ -36,7 +36,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: metrics
@@ -103,7 +103,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
 data:
@@ -144,6 +144,29 @@ data:
         done
         export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=$VOTERS
     fi
+    mkdir -p /opt/bitnami/kafka/config/certs
+    PEM_CA="/certs-${ID}/ca.crt"
+    PEM_CERT="/certs-${ID}/tls.crt"
+    PEM_KEY="/certs-${ID}/tls.key"
+    if [[ -f "$PEM_CERT" ]] && [[ -f "$PEM_KEY" ]]; then
+        CERT_DIR="/opt/bitnami/kafka/config/certs"
+        PEM_CA_LOCATION="${CERT_DIR}/kafka.truststore.pem"
+        PEM_CERT_LOCATION="${CERT_DIR}/kafka.keystore.pem"
+            if [[ -f "$PEM_CA" ]]; then
+                cp "$PEM_CA" "$PEM_CA_LOCATION"
+                cp "$PEM_CERT" "$PEM_CERT_LOCATION"
+            else
+                echo "PEM_CA not provided, and auth.tls.pemChainIncluded was not true. One of these values must be set when using PEM type for TLS."
+                exit 1
+            fi
+
+        # Ensure the key used PEM format with PKCS#8
+        openssl pkcs8 -topk8 -nocrypt -in "$PEM_KEY" > "/opt/bitnami/kafka/config/certs/kafka.keystore.key"
+    else
+        echo "Couldn't find the expected PEM files! They are mandatory when encryption via TLS is enabled."
+        exit 1
+    fi
+    export KAFKA_TLS_TRUSTSTORE_FILE="/opt/bitnami/kafka/config/certs/kafka.truststore.pem"
 
     # Configure zookeeper client
 
@@ -157,7 +180,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: metrics
@@ -187,7 +210,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: cluster-metrics
@@ -217,7 +240,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: kafka
@@ -251,7 +274,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: kafka
@@ -277,7 +300,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: cluster-metrics
@@ -292,7 +315,7 @@ spec:
     metadata:
       labels:
         app.kubernetes.io/name: kafka-shared
-        helm.sh/chart: kafka-22.0.3
+        helm.sh/chart: kafka-22.1.1
         app.kubernetes.io/instance: 22.0.0
         app.kubernetes.io/managed-by: Helm
         app.kubernetes.io/component: cluster-metrics
@@ -333,6 +356,10 @@ spec:
               --kafka.server=kafka-shared-0.kafka-shared-headless.pubsub.svc.cluster.local:9092 \
               --kafka.server=kafka-shared-1.kafka-shared-headless.pubsub.svc.cluster.local:9092 \
               --kafka.server=kafka-shared-2.kafka-shared-headless.pubsub.svc.cluster.local:9092 \
+              --tls.enabled \
+              --tls.key-file=/opt/bitnami/kafka-exporter/certs/tls.key \
+              --tls.cert-file=/opt/bitnami/kafka-exporter/certs/tls.crt \
+              --tls.ca-file=/opt/bitnami/kafka-exporter/certs/ca.crt \
               --web.listen-address=:9308
           ports:
             - name: metrics
@@ -341,7 +368,14 @@ spec:
             limits: {}
             requests: {}
           volumeMounts:
+            - name: kafka-exporter-certificates
+              mountPath: /opt/bitnami/kafka-exporter/certs/
+              readOnly: true
       volumes:
+        - name: kafka-exporter-certificates
+          secret:
+            secretName: kafka-exporter-cert
+            defaultMode: 0440
 ---
 # Source: kafka/templates/statefulset.yaml
 apiVersion: apps/v1
@@ -351,7 +385,7 @@ metadata:
   namespace: "pubsub"
   labels:
     app.kubernetes.io/name: kafka-shared
-    helm.sh/chart: kafka-22.0.3
+    helm.sh/chart: kafka-22.1.1
     app.kubernetes.io/instance: 22.0.0
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: kafka
@@ -371,12 +405,12 @@ spec:
     metadata:
       labels:
         app.kubernetes.io/name: kafka-shared
-        helm.sh/chart: kafka-22.0.3
+        helm.sh/chart: kafka-22.1.1
         app.kubernetes.io/instance: 22.0.0
         app.kubernetes.io/managed-by: Helm
         app.kubernetes.io/component: kafka
       annotations:
-        checksum/jmx-configuration: e5e2cd8c61712cabb61197754b96e8974f0f18b61446094975c96a2003e88fd8
+        checksum/jmx-configuration: 550ac38e32ea016567c2ad3960ac1fb954521f7105553275a704a44b11e7d911
     spec:
       
       hostNetwork: false
@@ -425,7 +459,7 @@ spec:
             - name: KAFKA_INTER_BROKER_LISTENER_NAME
               value: "INTERNAL"
             - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
-              value: "INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT"
+              value: "INTERNAL:SSL,CLIENT:SSL,CONTROLLER:SSL"
             - name: KAFKA_CFG_LISTENERS
               value: "INTERNAL://:9094,CLIENT://:9092,CONTROLLER://:9093"
             - name: KAFKA_CFG_ADVERTISED_LISTENERS
@@ -434,6 +468,14 @@ spec:
               value: "yes"
             - name: KAFKA_ZOOKEEPER_PROTOCOL
               value: PLAINTEXT
+            - name: KAFKA_TLS_TYPE
+              value: "PEM"
+            - name: KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
+              value: "https"
+            - name: KAFKA_TLS_CLIENT_AUTH
+              value: "required"
+            - name: KAFKA_CERTIFICATE_PASSWORD
+              value: ""
             - name: JMX_PORT
               value: "5555"
             - name: KAFKA_VOLUME_DIR
@@ -487,9 +529,9 @@ spec:
             - name: KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS
               value: "6000"
             - name: KAFKA_CFG_AUTHORIZER_CLASS_NAME
-              value: ""
+              value: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
             - name: KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND
-              value: "true"
+              value: "false"
             - name: KAFKA_CFG_SUPER_USERS
               value: "User:admin"
             - name: KAFKA_KRAFT_CLUSTER_ID
@@ -537,6 +579,15 @@ spec:
             - name: scripts
               mountPath: /scripts/setup.sh
               subPath: setup.sh
+            - name: kafka-certs-0
+              mountPath: /certs-0
+              readOnly: true
+            - name: kafka-certs-1
+              mountPath: /certs-1
+              readOnly: true
+            - name: kafka-certs-2
+              mountPath: /certs-2
+              readOnly: true
         - name: jmx-exporter
           image: docker.io/bitnami/jmx-exporter:0.18.0-debian-11-r18
           imagePullPolicy: "IfNotPresent"
@@ -573,6 +624,18 @@ spec:
         - name: jmx-config
           configMap:
             name: kafka-shared-jmx-configuration
+        - name: kafka-certs-0
+          secret:
+            secretName: kafka-shared-0-tls
+            defaultMode: 256
+        - name: kafka-certs-1
+          secret:
+            secretName: kafka-shared-1-tls
+            defaultMode: 256
+        - name: kafka-certs-2
+          secret:
+            secretName: kafka-shared-2-tls
+            defaultMode: 256
         - name: logs
           emptyDir: {}
   volumeClaimTemplates:
